export const CURRENCY_OPTIONS = [
  "AFN - Afghan Afghani",
  "ALL - Albanian Lek",
  "DZD - Algerian Dinar",
  "AOA - Angolan Kwanza",
  "ARS - Argentine Peso",
  "AMD - Armenian Dram",
  "AWG - Aruban Florin",
  "AZN - Azerbaijani Manat",
  "BSD - Bahamian Dollar",
  "BHD - Bahraini Dinar",
  "BDT - Bangladeshi Taka",
  "BBD - Barbadian Dollar",
  "BYN - Belarusian Ruble",
  "BZD - Belize Dollar",
  "BMD - Bermudian Dollar",
  "BTN - Bhutanese Ngultrum",
  "BOB - Bolivian Boliviano",
  "BAM - Bosnia & Herzegovina Convertible Mark",
  "BWP - Botswana Pula",
  "BRL - Brazilian Real",
  "BND - Brunei Dollar",
  "BGN - Bulgarian Lev",
  "BIF - Burundian Franc",
  "CVE - Cape Verdean Escudo",
  "KHR - Cambodian Riel",
  "KYD - Cayman Islands Dollar",
  "XAF - Central African CFA Franc",
  "XPF - CFP Franc",
  "CLP - Chilean Peso",
  "CNY - Chinese Yuan",
  "COP - Colombian Peso",
  "KMF - Comorian Franc",
  "CDF - Congolese Franc",
  "CRC - Costa Rican Colón",
  "HRK - Croatian Kuna",
  "CUP - Cuban Peso",
  "CZK - Czech Koruna",
  "DKK - Danish Krone",
  "DJF - Djiboutian Franc",
  "DOP - Dominican Peso",
  "XCD - East Caribbean Dollar",
  "EGP - Egyptian Pound",
  "ERN - Eritrean Nakfa",
  "SZL - Eswatini Lilangeni",
  "ETB - Ethiopian Birr",
  "FKP - Falkland Islands Pound",
  "FJD - Fijian Dollar",
  "GMD - Gambian Dalasi",
  "GEL - Georgian Lari",
  "GHS - Ghanaian Cedi",
  "GIP - Gibraltar Pound",
  "GTQ - Guatemalan Quetzal",
  "GNF - Guinean Franc",
  "GYD - Guyanese Dollar",
  "HTG - Haitian Gourde",
  "HNL - Honduran Lempira",
  "HKD - Hong Kong Dollar",
  "HUF - Hungarian Forint",
  "ISK - Icelandic Króna",
  "IDR - Indonesian Rupiah",
  "INR - Indian Rupee",
  "IRR - Iranian Rial",
  "IQD - Iraqi Dinar",
  "ILS - Israeli New Shekel",
  "JMD - Jamaican Dollar",
  "JPY - Japanese Yen",
  "JOD - Jordanian Dinar",
  "KZT - Kazakhstani Tenge",
  "KES - Kenyan Shilling",
  "KWD - Kuwaiti Dinar",
  "KGS - Kyrgyzstani Som",
  "LAK - Lao Kip",
  "LBP - Lebanese Pound",
  "LSL - Lesotho Loti",
  "LRD - Liberian Dollar",
  "LYD - Libyan Dinar",
  "LKR - Sri Lankan Rupee",
  "MOP - Macanese Pataca",
  "MKD - Macedonian Denar",
  "MGA - Malagasy Ariary",
  "MWK - Malawian Kwacha",
  "MYR - Malaysian Ringgit",
  "MVR - Maldivian Rufiyaa",
  "MRU - Mauritanian Ouguiya",
  "MUR - Mauritian Rupee",
  "MXN - Mexican Peso",
  "MDL - Moldovan Leu",
  "MNT - Mongolian Tögrög",
  "MAD - Moroccan Dirham",
  "MZN - Mozambican Metical",
  "MMK - Myanmar Kyat",
  "NAD - Namibian Dollar",
  "NPR - Nepalese Rupee",
  "ANG - Netherlands Antillean Guilder",
  "TWD - New Taiwan Dollar",
  "NZD - New Zealand Dollar",
  "NIO - Nicaraguan Córdoba",
  "NGN - Nigerian Naira",
  "KPW - North Korean Won",
  "NOK - Norwegian Krone",
  "OMR - Omani Rial",
  "PKR - Pakistani Rupee",
  "PAB - Panamanian Balboa",
  "PGK - Papua New Guinean Kina",
  "PYG - Paraguayan Guaraní",
  "PEN - Peruvian Sol",
  "PHP - Philippine Peso",
  "PLN - Polish Złoty",
  "QAR - Qatari Riyal",
  "RON - Romanian Leu",
  "RUB - Russian Ruble",
  "RWF - Rwandan Franc",
  "SHP - Saint Helena Pound",
  "WST - Samoan Tala",
  "STN - São Tomé and Príncipe Dobra",
  "SAR - Saudi Riyal",
  "RSD - Serbian Dinar",
  "SCR - Seychellois Rupee",
  "SLL - Sierra Leonean Leone",
  "SBD - Solomon Islands Dollar",
  "SOS - Somali Shilling",
  "ZAR - South African Rand",
  "KRW - South Korean Won",
  "SSP - South Sudanese Pound",
  "SRD - Surinamese Dollar",
  "SEK - Swedish Krona",
  "CHF - Swiss Franc",
  "SYP - Syrian Pound",
  "TJS - Tajikistani Somoni",
  "TZS - Tanzanian Shilling",
  "THB - Thai Baht",
  "TOP - Tongan Paʻanga",
  "TTD - Trinidad and Tobago Dollar",
  "TND - Tunisian Dinar",
  "TRY - Turkish Lira",
  "TMT - Turkmenistani Manat",
  "UGX - Ugandan Shilling",
  "UAH - Ukrainian Hryvnia",
  "AED - United Arab Emirates Dirham",
  "GBP - British Pound",
  "USD - United States Dollar",
  "UYU - Uruguayan Peso",
  "UZS - Uzbekistani Som",
  "VUV - Vanuatu Vatu",
  "VES - Venezuelan Bolívar",
  "VND - Vietnamese Đồng",
  "XOF - West African CFA Franc",
  "YER - Yemeni Rial",
  "ZMW - Zambian Kwacha",
  "ZWL - Zimbabwean Dollar",
];